server:
  port: 8888
spring:
  ai:
    mcp:
      client:
        enabled: true
        initialized: true
        name: ai-mcp-client
        sse:
          connections:
            server1:
              url: http://localhost:8081
        toolcallback:
          enabled: true
        type: sync

    openai:
      api-key: 111
      base-url: http://localhost:8080
      chat:
        options:
          max-tokens: 32768
          model: qwen2.5_32b
          temperature: 0.7

    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:3b
